### ISSUE TITLE
Requirementlist update

### ISSUE THREAD

**Issue by MS0x0539** [Yoruio/Membarr#21]
Hi,

Could you update the requirement list?
Would it work on the latest PlexAPI 4.13.0?

I'm not using virtual environments, so using membarr with PlexAPI 4.0.0 causes my other scripts to malfunction.

**Comment by Yoruio** [comment]
Should enable dependabot too to keep us updated

**Comment by Yoruio** [comment]
PlexAPI has been bumped up to 4.13.0 with #22
