### ISSUE TITLE
Getting Jellyfin Library update messege when using /plexsettings setuplibs <libraries>

### ISSUE THREAD

**Issue by ndroid007** [Yoruio/Membarr#24]
In command confirmation message it is saying updating jellyfin libraries

BOT  — Today at 4:07 PM
Jellyfin libraries updated. Please wait a few seconds for bot to restart.

Logs has below which is correct:
Plex libraries updated. Restarting bot. Please wait.

**Comment by Yoruio** [comment]
Fixed by #29
