### ISSUE TITLE
Jellyfin Setup Libs - String is Empty

### ISSUE THREAD

**Issue by ndroid007** [Yoruio/Membarr#27]
Error when trying to add libraries for jellyfin setup
![tempsnip](https://user-images.githubusercontent.com/116920731/198734785-9320c926-34d1-45c5-8f29-ac320382fb7b.png)

**Comment by Yoruio** [comment]
Thanks for the bug reports! Don't know how I missed these during testing

**Comment by ndroid007** [comment]
All good. I will be testing all the parts. Will get back if any other issues
