### ISSUE TITLE
the bot stopped starting

### ISSUE THREAD

**Issue by deadcxap** [Yoruio/Membarr#51]
Контейнер с ботом перестал стартовать. Конфигурацию не меняли, он просто вдруг взял и перестал запускаться((
Проверили, токен указан верный.
Логи контейнера:

> [2023-12-20 20:20:37] [INFO    ] discord.client: logging in using static token
> [2023-12-20 20:20:38] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 58122efe51c6b5e98f347faf72c11e2d).
> Traceback (most recent call last):
>   File "/app/run.py", line 346, in <module>
>     bot.run(Discord_bot_token)
>   File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 828, in run
>     asyncio.run(runner())
>   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 817, in runner
>     await self.start(token, reconnect=reconnect)
>   File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 746, in start
>     await self.connect(reconnect=reconnect)
>   File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 627, in connect
>     await self.ws.poll_event()
>   File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 622, in poll_event
>     await self.received_message(msg.data)
>   File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 572, in received_message
>     func(data)
>   File "/usr/local/lib/python3.9/site-packages/discord/state.py", line 1209, in parse_guild_create
>     guild = self._get_create_guild(data)
>   File "/usr/local/lib/python3.9/site-packages/discord/state.py", line 1147, in _get_create_guild
>     guild._from_data(data)
>   File "/usr/local/lib/python3.9/site-packages/discord/guild.py", line 487, in _from_data
>     self.stickers: Tuple[GuildSticker, ...] = tuple(
>   File "/usr/local/lib/python3.9/site-packages/discord/guild.py", line 488, in <lambda>
>     map(lambda d: state.store_sticker(self, d), guild.get('stickers', []))
>   File "/usr/local/lib/python3.9/site-packages/discord/state.py", line 379, in store_sticker
>     self._stickers[sticker_id] = sticker = GuildSticker(state=self, data=data)
>   File "/usr/local/lib/python3.9/site-packages/discord/sticker.py", line 273, in __init__
>     self._from_data(data)
>   File "/usr/local/lib/python3.9/site-packages/discord/sticker.py", line 416, in _from_data
>     super()._from_data(data)
>   File "/usr/local/lib/python3.9/site-packages/discord/sticker.py", line 280, in _from_data
>     self.url: str = f'{Asset.BASE}/stickers/{self.id}.{self.format.file_extension}'
>   File "/usr/local/lib/python3.9/site-packages/discord/enums.py", line 534, in file_extension
>     return lookup[self]
> KeyError: <StickerFormatType.unknown_4: 4>
> No Plex auth token details found
> No Plex login info found
> Could not load plex config
> Could not get Plex roles config
> Could not get Plex libs config. Defaulting to all libraries.
> Could not get Plex enable config. Defaulting to False
> Initializing Discord bot
> Loading media server connectors
> Connected to db
> Table exists.
> ------
> DB table version: Membarr V1.1
> DB table up to date!
> ------
> No Plex auth token details found
> No Plex login info found
> Could not load plex config
> Plex disabled. Skipping Plex login.

**Comment by tripout** [comment]
Had a similar issue. Was due to discord.py being out of date.

https://github.com/tripout/Membarr/commit/15ca18dd4ecbbcc550666f3231159fb718b2e551

**Comment by Yoruio** [comment]
discord.py has been updated to the latest version.
