### ISSUE TITLE
Unable to remove shared access from plex server..

### ISSUE THREAD

**Issue by cyb3rgh05t** [Yoruio/Membarr#53]
Hi,

seems that plex changed something to remove users from plex server.

```
(410) gone; https://plex.tv/api/friends/27895919 <?xml version="1.0" encoding="UTF-8"?> <Response code="410" status="This endpoint was deprecated and removed"/>
Removed Plex email cyb3rgh05t from db
```

is it possible to fix this?

**Comment by ifelsee101** [comment]
PlexAPI needs to be updated

**Comment by cyb3rgh05t** [comment]
yes got it thanks :)

**Comment by yaitsbilly** [comment]
I'm also having this issue. Is there a fix in the works?

**Comment by endrence3** [comment]
PlexAPI Needs to update @Yoruio . Please update it!

**Comment by Yoruio** [comment]
PlexAPI has been updated in the repo.
